Import('env', 'arch', 'common', 'messaging', 'rednose', 'transformations')

loc_libs = [messaging, common, 'pthread', 'dl']

# build ekf models
rednose_gen_dir = 'models/generated'
rednose_gen_deps = [
  "models/constants.py",
]
live_ekf = env.RednoseCompileFilter(
  target='live',
  filter_gen_script='models/live_kf.py',
  output_dir=rednose_gen_dir,
  extra_gen_artifacts=['live_kf_constants.h'],
  gen_script_deps=rednose_gen_deps,
)

# locationd build
locationd_sources = ["locationd.cc", "models/live_kf.cc"]

lenv = env.Clone()
# ekf filter libraries need to be linked, even if no symbols are used
if arch != "Darwin":
  lenv["LINKFLAGS"] += ["-Wl,--no-as-needed"]

lenv["LIBPATH"].append(Dir(rednose_gen_dir).abspath)
lenv["RPATH"].append(Dir(rednose_gen_dir).abspath)
locationd = lenv.Program("locationd", locationd_sources, LIBS=["live", "ekf_sym"] + loc_libs + transformations)
lenv.Depends(locationd, rednose)
lenv.Depends(locationd, live_ekf)

if GetOption('extras'):
  test_env = lenv.Clone()
  test_env.Append(CPPDEFINES=['LOCATIOND_UNIT_TEST'])
  test_env.Program(
    'tests/test_locationd_gps_input_safety',
    [
      'tests/test_locationd_gps_input_safety.cc',
      test_env.Object('tests/locationd_ut', 'locationd.cc'),
      test_env.Object('tests/live_kf_ut', 'models/live_kf.cc'),
    ],
    LIBS=["live", "ekf_sym"] + loc_libs + transformations,
  )
